# Generated by Django 4.2 on 2025-10-13 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_remove_contact_help_contact_applications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_person_email',
        ),
    ]
