# Generated by Django 4.2 on 2025-10-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_remove_contact_contact_person_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsletterSubscription',
        ),
    ]
