# Generated by Django 6.0.2 on 2026-02-22 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal tag name (lowercase, no spaces)', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the tag', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Article title', max_length=255, unique=True)),
                ('slug', models.SlugField(help_text='URL-friendly version of title', max_length=255, unique=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO meta title', max_length=255)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=500)),
                ('main_image', models.ImageField(blank=True, help_text='Main article image', null=True, upload_to='blog/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False, help_text='Whether the article is published')),
                ('published_at', models.DateTimeField(blank=True, help_text='Publication date', null=True)),
                ('main_tag', models.ForeignKey(blank=True, help_text='Primary tag for this article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_articles', to='blog.tag')),
                ('other_tags', models.ManyToManyField(blank=True, help_text='Additional tags', related_name='articles', to='blog.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', 'Text (HTML)'), ('image', 'Image')], help_text='Type of content block', max_length=10)),
                ('content', models.TextField(help_text='HTML content for text blocks or image URL/path for image blocks')),
                ('image', models.ImageField(blank=True, help_text='Image file (for image blocks)', null=True, upload_to='blog/blocks/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of the block in the article')),
                ('article', models.ForeignKey(help_text='Article this block belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='blog.article')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('article', 'order')},
            },
        ),
    ]
