# Generated by Django 6.0.2 on 2026-02-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='meta_title',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.RemoveField(
            model_name='block',
            name='content',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='display_name',
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_en',
            field=models.TextField(blank=True, help_text='SEO meta description in English', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_description_it',
            field=models.TextField(blank=True, help_text='SEO meta description in Italian', max_length=500),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_en',
            field=models.CharField(blank=True, help_text='SEO meta title in English', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='meta_title_it',
            field=models.CharField(blank=True, help_text='SEO meta title in Italian', max_length=255),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(default='asd', help_text='Article title in English', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title_it',
            field=models.CharField(default='asd', help_text='Article title in Italian', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='content_en',
            field=models.TextField(blank=True, help_text='HTML content in English (for text blocks)'),
        ),
        migrations.AddField(
            model_name='block',
            name='content_it',
            field=models.TextField(blank=True, help_text='HTML content in Italian (for text blocks)'),
        ),
        migrations.AddField(
            model_name='tag',
            name='display_name_en',
            field=models.CharField(default='asd', help_text='Display name in English', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='display_name_it',
            field=models.CharField(default='asd', help_text='Display name in Italian', max_length=100),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('title_it',), name='unique_title_it'),
        ),
        migrations.AddConstraint(
            model_name='article',
            constraint=models.UniqueConstraint(fields=('title_en',), name='unique_title_en'),
        ),
    ]
