# Generated by Django 6.0.2 on 2026-02-25 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_article_meta_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name_it', models.CharField(help_text='Display name in Italian', max_length=100)),
                ('display_name_en', models.CharField(help_text='Display name in English', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_name_it'],
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='main_tag',
        ),
        migrations.RemoveField(
            model_name='article',
            name='other_tags',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Article tags', related_name='articles', to='blog.tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey( help_text='Article category', on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.category'),
            preserve_default=False,
        ),
    ]
